apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: https://prod.sm.eu01.stackit.cloud
      path: "ace9d260-da76-4f6f-8cc7-1746eb83593f"
      version: v2
      auth:
        userPass:
          path: userpass
          username: "sme160l0dt3c13z6"
          secretRef:
            name: vault-secret
            key: PASSWORD
            namespace: kube-system
